"""Custom exceptions package"""
from .custom_exceptions import (
    AppException,
    AuthenticationException,
    UserNotFoundException,
    UserNotApprovedException,
    InvalidCredentialsException,
    AccountLockedException,
    AccountInactiveException,
    OTPException,
    InvalidOTPException,
    OTPExpiredException,
    OTPSendFailedException,
    OTPUserNotFoundException,
    ResendOTPInvalidUserException,
    ResendOTPUserNotApprovedException,
    ResendOTPFailedException,
    UserManagementException,
    UserGetNotFoundException,
    UserApproveNotFoundException,
    UserRejectNotFoundException,
    UserUpdateNotFoundException,
    UserUpdateForbiddenException,
    RegistrationException,
    EmailAlreadyExistsException,
    PasswordMismatchException,
    RegistrationEmailFailedException,
    DatabaseException,
    DatabaseQueryException,
    IntegrityConstraintException,
    EmailServiceException,
    TemplateNotFoundException,
    TemplateRenderException,
    TokenException,
    InvalidTokenException,
    TokenExpiredException,
    UserFromTokenNotFoundException,
    # Password Reset exceptions
    PasswordResetException,
    PasswordResetUserNotFoundException,
    InvalidResetTokenException,
    ResetTokenExpiredException,
    PasswordResetFailedException,
    PasswordResetRateLimitException,
    ResetPasswordMismatchException,
    ResetWeakPasswordException,
    ResetUserNotApprovedException,
    ResetAccountLockedException,
    # Authorization exceptions
    AuthorizationException,
    AuthenticationRequiredException,
    AdminRoleRequiredException,
    ManagerRoleRequiredException,
    UserRoleRequiredException,
    InsufficientPermissionsException,
    CompanyAccessForbiddenException,
    ManagerApprovalOnlyException,
    ManagerShipmentManagementOnlyException,

    # Task exceptions
    TaskException,
    TaskCreateFailedException,
    TaskNotFoundException,
    TaskInvalidAssigneeException,
    TaskInvalidPatientException,
    TaskUpdateFailedException,
    TaskDeleteFailedException,
    TaskUnauthorizedEditException,
    TaskUnauthorizedStatusException,
    TaskManagerOnlyException
)

__all__ = [
    'AppException',
    'AuthenticationException',
    'UserNotFoundException',
    'UserNotApprovedException',
    'InvalidCredentialsException',
    'AccountLockedException',
    'AccountInactiveException',
    'OTPException',
    'InvalidOTPException',
    'OTPExpiredException',
    'OTPSendFailedException',
    'OTPUserNotFoundException',
    'ResendOTPInvalidUserException',
    'ResendOTPUserNotApprovedException',
    'ResendOTPFailedException',
    'UserManagementException',
    'UserGetNotFoundException',
    'UserApproveNotFoundException',
    'UserRejectNotFoundException',
    'UserUpdateNotFoundException',
    'UserUpdateForbiddenException',
    'RegistrationException',
    'EmailAlreadyExistsException',
    'PasswordMismatchException',
    'RegistrationEmailFailedException',
    'DatabaseException',
    'DatabaseQueryException',
    'IntegrityConstraintException',
    'EmailServiceException',
    'TemplateNotFoundException',
    'TemplateRenderException',
    'TokenException',
    'InvalidTokenException',
    'TokenExpiredException',
    'UserFromTokenNotFoundException',
    # Password Reset exceptions
    'PasswordResetException',
    'PasswordResetUserNotFoundException',
    'InvalidResetTokenException',
    'ResetTokenExpiredException',
    'PasswordResetFailedException',
    'PasswordResetRateLimitException',
    'ResetPasswordMismatchException',
    'ResetWeakPasswordException',
    'ResetUserNotApprovedException',
    'ResetAccountLockedException',
    # Authorization exceptions
    'AuthorizationException',
    'AuthenticationRequiredException',
    'AdminRoleRequiredException',
    'ManagerRoleRequiredException',
    'UserRoleRequiredException',
    'InsufficientPermissionsException',
    'CompanyAccessForbiddenException',
    'ManagerApprovalOnlyException',
    'ManagerShipmentManagementOnlyException',

    # Task exceptions
    'TaskException',
    'TaskCreateFailedException',
    'TaskNotFoundException',
    'TaskInvalidAssigneeException',
    'TaskInvalidPatientException',
    'TaskUpdateFailedException',
    'TaskDeleteFailedException',
    'TaskUnauthorizedEditException',
    'TaskUnauthorizedStatusException',
    'TaskManagerOnlyException',
]

# Quality monitoring exceptions
from .quality_exceptions import (
    QualityException,
    RedisConnectionException,
    QualityDataNotFoundException,
    QualityServiceException,
)

__all__.extend([
    'QualityException',
    'RedisConnectionException',
    'QualityDataNotFoundException',
    'QualityServiceException',
])

