version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mygrape
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: suriya2002
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mygrape
      - DB_USER=postgres
      - DB_PASSWORD=suriya2002
    volumes:
      - ../src:/app/src
      - ../static:/app/static

volumes:
  postgres_data:
