name: Build, Push & Deploy Docker Image - mgscale-alerting-service-prod

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  build-push-deploy:
    uses: ./.github/workflows/reusable-azure-webapp-docker.yml
    with:
      app_name: mgscale-alerting-service-prod
      acr_login_server: mgscaleprod.azurecr.io
      acr_username: mgscaleprod
      image_name: mgscale-backend
      context_path: ./backend
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      ACR_PASSWORD: ${{ secrets.ACR_ADMIN_PASSWORD_PROD }}

