name: Build, Push & Deploy Docker Image - mgscale-backend-dev

on:
  push:
    branches:
      - develop
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  build-push-deploy:
    uses: ./.github/workflows/reusable-azure-webapp-docker.yml
    with:
      app_name: mgscale-backend-service-dev
      acr_login_server: myscaledev.azurecr.io
      acr_username: myscaledev
      image_name: mgscale-backend
      context_path: ./backend
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      ACR_PASSWORD: ${{ secrets.ACR_ADMIN_PASSWORD }}



